config/routes.rb
Rails.application.routes.draw do

  get 'sections/index'

  get 'sections/show'

  get 'sections/new'

  get 'sections/edit'

  get 'sections/delete'

  get 'pages/index'

  get 'pages/show'

  get 'pages/new'

  get 'pages/edit'

  get 'pages/delete'

  root 'demo#index'

  resources :subjects do 

    member do 
      get :delete 
    end

  end

  

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'

  #match "demo/index", :to => "demo#index",
     #:via => :get
  #get ':controller(/:action(/:id))'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

    #self.table_name = "admin_users"
    has_and_belongs_to_many :pages
    has_many :section_edits

    has_many :sections, :through => :section_edits
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

     belongs_to :subject, {:optional => false}
     has_many :sections
     has_and_belongs_to_many :admin_users

     scope :visible, lambda { where(:visible => true) }
     scope :invisible, lambda { where(:visible => false) }
     scope :sorted, lambda { order("position ASC") }
     scope :newest_first, lambda { order("created_at DESC") }
     

end

app/models/section.rb
class Section < ApplicationRecord
    belongs_to :page
    has_many :section_edits

    has_many :admin_users, :through => :section_edits

    scope :visible, lambda { where(:visible => true) }
    scope :invisible, lambda { where(:visible => false) }
    scope :sorted, lambda { order("position ASC") }
    scope :newest_first, lambda { order("created_at DESC") }
end

app/models/section_edit.rb
class SectionEdit < ApplicationRecord
    belongs_to :admin_user
    belongs_to :section
end

app/models/subject.rb
class Subject < ApplicationRecord

    has_many :pages

    scope :visible, lambda { where(:visible => true)}
    scope :invisible, lambda { where(:visible => false)}
    scope :sorted, lambda {order("position ASC")}
    scope :newest_first, lambda {order("created_at DESC")}
    scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"])}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  layout false
  
  def index
    render('index')
  end

  def hello
    @array = [1,2,3,4,5]
    @id = params['id']
    @page = params[:page]
    render('hello')
  end


  def other_hello
    redirect_to(:action => 'hello')
  end

  def lynda
    redirect_to('http://lynda.com')
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.sorted
  end

  def show
  end

  def new
  end

  def edit
  end

  def delete
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def delete
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def index
    @subjects = Subject.sorted
  end

  def show
    @subject = Subject.find(params[:id])
  end
  #display the form
  def new
    @subject = Subject.new({:name => 'Default'})
  end
  #create the form
  def create
    #instantiate a new object using form parameters
    @subject = Subject.new(subject_params)
    #save the object
    if @subject.save
      #if save succeeds, redirect to the index action
      flash[:notice] = "Subject created successfully"
      redirect_to(subjects_path)
    else
      #if save fails, redisplay the form so user can fix the problems

      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    #instantiate a new object using form parameters
    @subject = Subject.find(params[:id])
    #save the object
    if @subject.update_attributes(subject_params)
      #if save succeeds, redirect to the index action
      flash[:notice] = "Subject Updated successfully"
      redirect_to(subject_path(@subject))
    else
      #if save fails, redisplay the form so user can fix the problems

      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject '#{@subject.name}' destroyed successfully"
    redirect_to(subjects_path)
  end


  private 

  def subject_params
    params.require(:subject).permit(:name, :position, :visible)
  end

end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/demo/hello.html.erb
<h1>Hello World From Hello</h1>


<%= link_to('Index', {:action => 'index'})%><br/>

<br/>

ID: <%=@id %><br/>
ID: <%= params[:id]%><br/>
Page: <%=@page%><br/>
Next page: <%= @page.to_i + 1%><br />

app/views/demo/index.html.erb
<h1>Hello World! from Index</h1>

<a href="/demo/hello">Hello page 1</a><br/>

<%= link_to('Hello page 2', {:action => 'hello'})%><br/>

<%= link_to('Hello with parameters', {:action => 'hello', :page => 5, :id => 20})%><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/delete.html.erb
<h1>Pages#delete</h1>
<p>Find me in app/views/pages/delete.html.erb</p>

app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/new.html.erb
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/sections/delete.html.erb
<h1>Sections#delete</h1>
<p>Find me in app/views/sections/delete.html.erb</p>

app/views/sections/edit.html.erb
<h1>Sections#edit</h1>
<p>Find me in app/views/sections/edit.html.erb</p>

app/views/sections/index.html.erb
<h1>Sections#index</h1>
<p>Find me in app/views/sections/index.html.erb</p>

app/views/sections/new.html.erb
<h1>Sections#new</h1>
<p>Find me in app/views/sections/new.html.erb</p>

app/views/sections/show.html.erb
<h1>Sections#show</h1>
<p>Find me in app/views/sections/show.html.erb</p>

app/views/subjects/delete.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Subject</h2>

  <%= form_for(@subject, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this subject?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/edit.html.erb
<<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update Subject</h2>

  <%= form_for(@subject) do |f| %>

    <table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.text_field(:position) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>


<div class="subjects index">
  <h2>Subjects</h2>

  <%= link_to("Add New Subject", new_subject_path, :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= subject.visible ? 'Yes' : 'No' %></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
        <%= link_to("Show", subject_path(subject), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Subject</h2>

  <%= form_for(@subject) do |f| %>

    <table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.text_field(:position) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/show.html.erb
<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>


<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>

</div>